### ISSUE TITLE
Milestone Created

### ISSUE THREAD

**Issue by LiamMahoney** [LiamMahoney/scrummy#25]
When a milestone is created, a new project should be created based on a copy of the template project board with the same name as the milestone. 

This will be a 'sprint' board.

This should **not** create a `project: <project>` label.

**Need to make sure this plays nicely with milestones getting reopened.**

## Hook

**hook:** milestone
**action:** created

## Actions

- [x] get milestone name

- [x] find the template project

- [x] prevent project label from being made

- [x] create copy of template project with the same name as the milestone

**Comment by LiamMahoney** [comment]
Data sent on copy project request:

```
------WebKitFormBoundaryW5tU7b6bIjYbYxKy
Content-Disposition: form-data; name="authenticity_token"

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx+H4dC7QGEWkrWX5FelHmoE2TGu9QiKMtCKgPJRx2R/YEJMAtAZrWdf9bOQ==
------WebKitFormBoundaryW5tU7b6bIjYbYxKy
Content-Disposition: form-data; name="project[global_target_owner_id]"

MDEwOlJlcG9zaXRvcnkyNDUwNTcyMDI=
------WebKitFormBoundaryW5tU7b6bIjYbYxKy
Content-Disposition: form-data; name="project[name]"

Copy Test
------WebKitFormBoundaryW5tU7b6bIjYbYxKy
Content-Disposition: form-data; name="project[body]"

Using this to figure out what request it made when creating a copy of a template.
------WebKitFormBoundaryW5tU7b6bIjYbYxKy
Content-Disposition: form-data; name="project[include_workflows]"

0
------WebKitFormBoundaryW5tU7b6bIjYbYxKy
Content-Disposition: form-data; name="project[include_workflows]"

1
------WebKitFormBoundaryW5tU7b6bIjYbYxKy
Content-Disposition: form-data; name="project[public]"

false
------WebKitFormBoundaryW5tU7b6bIjYbYxKy
Content-Disposition: form-data; name="project[global_source_id]"

MDc6UHJvamVjdDQwNzg4OTc=
------WebKitFormBoundaryW5tU7b6bIjYbYxKy
Content-Disposition: form-data; name="client_uid"

6afb4756e7028dfe00eb14b5a116483c
------WebKitFormBoundaryW5tU7b6bIjYbYxKy
Content-Disposition: form-data; name="redirect_back"

true
------WebKitFormBoundaryW5tU7b6bIjYbYxKy--
```

**Comment by LiamMahoney** [comment]
Use the Graphql API to [clone the template project](https://developer.github.com/v4/mutation/cloneproject/).

**Comment by LiamMahoney** [comment]
Milestone project creation is working.

Need to stop the 'project: <project>' label from being created. Need to add a milestone check in the project created functionality

**Comment by LiamMahoney** [comment]
Not creating a `project: <project>` label for the milestone project any longer
