### ISSUE TITLE
Issue Added to Milestone

### ISSUE THREAD

**Issue by LiamMahoney** [LiamMahoney/scrummy#29]
When an issue is added to a milestone, the issue should be added to that milestone's sprint board.

## Hooks

**Hook:** issues
**Action:** milestoned

## Actions

- [x] get all of the project boards in the repository

- [x] match a project board to the milestone the issue was added to

- [x] if there is a stage label on the issue, add the issue to that column in the project

~~- [ ] if there isn't a stage label, add it to the first column(?) - maybe get first column in the template project (if they come in order?)~~ removing this until I can think of a better way

**Comment by LiamMahoney** [comment]
Writing some terrible code that's going to need to be refactored asap.

**Comment by LiamMahoney** [comment]
Throwing error that the `project: <project>` label can't be found for the milestone projects. I don't think I want milestone project labels (issues are already in the milestone) so this is expected behavior. Is this an acceptable way to handle it though?

**Comment by LiamMahoney** [comment]
Might be able to use the graphql API to get the `column purpose` and then I could just auto add to the TODO column. The `project_card created` action would take over and move it to the correct column, if needed 

Or if I don't want to mess around with getting the 'column purpose' it looks like the columns get returned in the correct order they are laid out in the project. Could just add it to column in index 0 

In order for this to work I need to refactor the function `findProjectLabel` so it doesn't throw an error if no project labels are found. This means anything that calls the function will now have to check if the result. Can't depend on the error being thrown if no label is found. Making me think about whether i should be logging in lower end functions rather than only at the top. Most of the errors are happening because I want to log a certain message..

**Comment by LiamMahoney** [comment]
Made some changes to `projectCardCreated` but I'm not very happy with them.. Code is not very straightforward. 

Thinking I should rewrite `projectCardCreated` to check if the name of the project the project card was added to matches a milestone.
* if it does, call new function ~ milestoneProjectCardCreated that just calls `findNewProjectCardStage`
* if it doesn't, call new function ~ that calls what is currently `projectCardCreated`

**Comment by LiamMahoney** [comment]
Refactored a bit and it's much easier to understand. However, there may be some wasted requests. Going to leave it for now

**Comment by LiamMahoney** [comment]
Need to add debug log statements in every action. 

Getting 

```txt
2020-04-16 22:20:25 [error] Error: expected 201 received 422 - POST /projects/columns/8259336/cards: Validation Failed
    at Object.handleRest (/var/www/scrummy/utils/request.js:162:19)
    at Object.addIssueToProject (/var/www/scrummy/core/actions/issue.js:175:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async **projectLabelAddedToIssue** (/var/www/scrummy/core/states/issue.js:487:32)
    at async Object.issueLabeled (/var/www/scrummy/core/states/issue.js:319:24)
    at async issues (/var/www/scrummy/core/hooks/issues.js:19:24)
    at async determineHook (/var/www/scrummy/core/scrummy.js:24:24)
    at async scrummy (/var/www/scrummy/core/scrummy.js:40:20)
```

So getting a loop when an issue is added to a project..

**Comment by LiamMahoney** [comment]
Added `isIssueInProject` function to prevent the loop above. Appears to be working. Need to test further
