### ISSUE TITLE
Milestone Closed

### ISSUE THREAD

**Issue by LiamMahoney** [LiamMahoney/scrummy#31]
When a milestone is closed, all of the issues in that milestone should be removed and the milestone's project board should be closed.

## Hook

**hook:** milestone
**action:** closed

## Actions

- [x] close the project

- [x] get all milestone items 

- [x] remove each item from the milestone

**Comment by LiamMahoney** [comment]
The `open_issues` field that is passed in the payload of the webhook is a count of the issues + pull requests on the milestone. Going to use this on how many of the issues / pull requests to retrieve in the graphql request to get all issues / PRs in a milestone.

**Comment by LiamMahoney** [comment]
Just finished getting all of the milestone items in `states/milestone.js`. Now I need to go through each item and remove the milestone from it.

[remove issue](https://developer.github.com/v3/issues/#update-an-issue)
[note about prs](https://developer.github.com/v3/pulls/#labels-assignees-and-milestones)

**Comment by LiamMahoney** [comment]
Here's an example response from the function `Milestone.getMilestoneItems`

```
{
  "data": {
    "repository": {
      "milestone": {
        "issues": {
          "nodes": [
            {
              "title": "test project card in different column test",
              "databaseId": 587356393,
              "number": 24
            },
            {
              "title": "converted project card test",
              "databaseId": 587356190,
              "number": 23
            }
          ]
        },
        "pullRequests": {
          "nodes": [
            {
              "title": "init",
              "databaseId": 407616100,
              "number": 33
            }
          ]
        }
      }
    }
  }
}
```

**Comment by LiamMahoney** [comment]
removing milestone from issue

**Comment by LiamMahoney** [comment]
removing milestone from pull request

**Comment by LiamMahoney** [comment]
Got the following error when closing a milestone that had a pull request in it: 

```
2020-05-14 01:01:31 [error] Error: Could not resolve to an Issue with the number of 35.
    at Object.handleQL (/var/www/scrummy/utils/request.js:238:19)
    at Object.getIssueProjectCards (/var/www/scrummy/core/actions/issue.js:143:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.issueDemilestoned (/var/www/scrummy/core/states/issue.js:763:28)
    at async issues (/var/www/scrummy/core/hooks/issues.js:25:24)
    at async determineHook (/var/www/scrummy/core/scrummy.js:24:24)
    at async scrummy (/var/www/scrummy/core/scrummy.js:42:20)
```
