### ISSUE TITLE
Issue Removed from Milestone

### ISSUE THREAD

**Issue by LiamMahoney** [LiamMahoney/scrummy#32]
When an issue is removed from a milestone, the issue's associated project card should be removed from that Milestone's project board.

**Needs to only happen on active milestones** so milestone project boards are preserved after the milestone is closed (#31).

## Hook

**Hook:** issues
**Action:** demilestoned

## Actions

- [x] get all of the issue's project cards

- [x] find the project card that's in the milestone project the issue was just removed from

- [x] make sure the project is active

- [x] delete that project card

**Comment by LiamMahoney** [comment]
appears to be working

**Comment by LiamMahoney** [comment]
Checking if the milestone project is open before deleting the project card is working.

This is needed to keep the history of a closed milestone intact. When a milestone is closed a 'snapshot' of the milestone progress at the moment it was closed is kept in the milestone project.
